"""Update field birthday 

Revision ID: 41e548604ec4
Revises: dc5ed550c0c0
Create Date: 2025-03-19 23:16:35.920887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41e548604ec4'
down_revision: Union[str, None] = 'dc5ed550c0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('birthday', sa.Date(), nullable=False))
    op.drop_column('contacts', 'date_of_birth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('contacts', 'birthday')
    # ### end Alembic commands ###
